root = "."
tmp_dir = "/tmp"

[build]
    cmd = "go build -o ./bin/main ."
    bin = "bin/main"
    full_build_log = true
    delay = 800
    poll = true
    poll_interval = 300

[log]
    color = true
    show_timestamp = true
    time_format = "15:04:05"

[color]
    main = "magenta"
    info = "gray"
    error = "red"
    warning = "yellow"
    time = "blue"